/**
 * Feature flags configuration.
 * This file is generated by cookiecutter based on project options.
 * Features can be checked at runtime to conditionally render components.
 */

export const FEATURES = {
  copilot: {% if cookiecutter.copilot_ui == "True" or cookiecutter.copilot_ui == true %}true{% else %}false{% endif %},
  // Add more feature flags here as needed
  // auth: {% if cookiecutter.no_auth == "False" or cookiecutter.no_auth == false %}true{% else %}false{% endif %},
} as const;

export type FeatureKey = keyof typeof FEATURES;

/**
 * Check if a feature is enabled.
 */
export function isFeatureEnabled(feature: FeatureKey): boolean {
  return FEATURES[feature];
}
